export const textosCartas = {
  
  margarita: {
    titulo: "La flor de los recuerdos",
    cuerpo: `Se me hace un poco inusual empezar esta experiencia así, ya que la he dividido en cuatro momentos diferentes para mostrarte poco a poco todo lo que quiero expresar. Para comenzar, estoy casi seguro de que estas no son las flores amarillas que esperabas. Sé que, a raíz de la distancia, me veo limitado para hacer todo lo que quisiera, pero, para serte sincero, lo que más me limita es el dinero.

Sin embargo, independientemente de cualquier dificultad, nada me detendrá de intentar hacerte un bonito detalle. En realidad, estoy usando este día solo como una excusa para darte algo que ya tenía pensado previamente. Es cierto que conmigo estás viviendo la experiencia de “POV: eres novia del programador”, pero busco de muchas maneras darte regalos diferentes para que no sientas que siempre hago lo mismo. Aunque, en el fondo, creo que incluso si fuera siempre igual, también te gustaría. El punto es innovar, encontrar todas las formas que se me ocurran para contarte lo que me pasa por la cabeza o, si nos ponemos un poco más románticos, por el corazón.

He leído tu carta muchas veces, y hace poco fue una de ellas. Me puse a pensar en lo interesante que fue cómo hiciste referencias a tu carrera, a esa parte de tu vida que se basa tanto en estudiar. Para mí, tiene mucho sentido que juntes medicina con romanticismo, ya que al final, uno de esos dos temas lo controlas a la perfección y el otro, por lo que has dicho, te cuesta un poco más.

Sentí que tu forma de hablar en aquella carta te representaba por completo; demostraba que no eras simplemente alguien que, sin saber cómo expresar sus sentimientos, se estancaría en lo mismo de siempre. En el momento en que leí todo lo que escribiste, supe que esos sentimientos existían en ti, esa forma de pensar que me confirmaba que, aunque no lo pareciera inicialmente, yo era importante para ti de alguna manera.

Soy plenamente consciente de que justo ese día no fue el mejor de nuestra relación, pero te soy muy sincero cuando digo que, en ese momento, estaba muy entusiasmado. Creo que, indirectamente, fue por eso que terminé hablando de otros temas que no tenían que ver con la situación. No quiero profundizar en esto, porque ambos sabemos lo que pasó, y esta no es una carta para pedirte perdón una vez más.

Estuve pensando mucho en la temática de todo esto, y llegué a una conclusión: Candy Candy. Sí, estarás viendo muchas referencias a esa serie, tanto en el texto como en la decoración de esta carta en concreto. Esto ocurre porque para mí fue muy importante que viéramos todos los episodios juntos. Te lo mencioné en su momento, pero quiero que entiendas que la razón no era la serie en sí, ni el hecho de que terminara. De hecho, si esa serie hacía que pasáramos más tiempo juntos, nunca querría que se acabara.

Para mí, todo se reduce al tiempo que compartimos y a las cosas que podemos o no hacer debido a nuestra situación. Me encantaría llevarte al cine, a un parque, a un centro comercial, a una obra de teatro, a la playa, a un pueblo perdido... Me encantaría vivir todo tipo de experiencias contigo, pero estoy limitado. Y aun con esas limitaciones, hemos logrado ver series y películas, jugar juntos, hablar por días enteros o simplemente dormir en llamada, pasando todo el tiempo que nos mantiene unidos. Ya lo hemos mencionado, pero no deja de ser relevante: no estamos juntos solo por pasar el rato. La realidad es que yo paso tiempo contigo porque amo dedicarte todo el tiempo que sea posible; quiero estar a tu lado y apoyarte en todo.

Recuerdo que, cuando te conocí, sentí un gran entusiasmo por mostrarte un mundo infinito de juegos. Recuerdo escucharte y darme cuenta de que te faltaba mucho por conocer, y una parte de mí anhelaba enseñarte el mundo, aunque quizás en ese momento no era algo tan específico como ahora. Pero todo me guiaba a mostrarte que la vida no tiene por qué ser una línea recta en la que solo sigues patrones, uno detrás del otro. No me malinterpretes, es importante seguir un camino, pero en términos de relaciones, "amar" suele tener un significado mucho más abierto.

Hasta ahora, mi forma de quererte ha sido mostrarte mi mundo. El momento más increíble que recuerdo de haberte mostrado algo fue con Interestelar. Sé que WALL-E te gustó más, pero Interestelar es mi película favorita, y ver que sentiste tanto al verla conmigo fue una experiencia que nunca olvidaré. No solo por el hecho de que lloraste, sino porque realmente te noté ahí, concentrada, sabiendo que ese momento era solo nuestro. No importaba el poco tiempo que lleváramos conociéndonos, ni la relación que teníamos, ni siquiera la duración de la película. Simplemente, en esa situación, éramos tú y yo.

Puede que me esté desviando del objetivo, pero para llegar a esta carta, viste mi pobre intento de margarita. Tiene un significado: después de investigar, descubrí que la margarita simboliza el renacer. Quizás no tiene mucho sentido con lo que he dicho hasta ahora, pero para mí, toda nuestra situación y las vivencias que hemos tenido han llevado a un nuevo renacer, han generado algo nuevo que nos ha traído hasta aquí. No quiere decir que esto sea un antes y un después (aunque tal vez sí), pero me alegro de estar aquí, contigo.

Sin mucho más que añadir, te daré la pista para la siguiente palabra. Será algo simple: es el nombre de la siguiente flor, y la pista es que hay un dios griego con ese mismo nombre.`
  },

narciso: {
    titulo: "Flor de la Enseñanza",
    cuerpo1: `Hasta este punto de mi vida, me he dado cuenta de que te he enseñado mucho, no solo por lo que yo crea, sino por lo que tú misma me has dicho. Verás muchas referencias a tu propia carta aquí, porque es lo más cercano que he visto a tu forma de expresarte.

Hace poco, ocurrió algo que me dejó pensando, no sobre mis sentimientos, sino sobre cómo decírtelos. Por mucho tiempo, planeé todo este tipo de cartas y formas de expresión para decirte una sola cosa. Pero un día, sin esperármelo, me lo preguntaste directamente. Y, claramente, no puedo negarme si me preguntas de forma directa si estoy enamorado de ti. Mi respuesta claramente será que sí; no hay ningún contexto en el que pueda decir que no teniendo en cuenta como me siento actualmente. Podría haberme hecho el difícil, negarlo y luego confirmarlo con una carta, pero contigo también he aprendido mucho.

Aunque parezca que solo soy yo el que te enseña, no siempre es porque me digas algo directamente. Simplemente, el estar contigo, verte como eres y saber cómo soy yo a diferencia de ti, me hace ver que no debo tener miedo de expresar lo que siento. Al mismo tiempo, me gusta ser testigo de tu progreso emocional; me encanta ver cómo, de repente, puedes decirme una palabra bonita sin que yo tenga que pedirla, aunque sabes que a veces me gusta confirmar si aún me quieres.

Fuera de todo eso, mi forma de expresarme contigo también se basa mucho en canciones, y creo que no faltarán aquí. Justo esta encaja muy bien en esta parte, así que aquí te la`,
palabraLink: ` dejo.`,
    cuerpo2: `

Ahora solo quiero argumentar un poco más lo que dije en la primera carta: me interesa mucho mostrarte el mundo del amor, a mi manera. Espero no hacerlo nunca de forma forzada o que te sientas presionada; siempre he intentado que sea algo tranquilo, lindo y, en general, una buena experiencia para ti. Estoy abierto a que me conozcas de todas las formas posibles, al igual que yo siento una gran curiosidad por ti. Eres mi gloria, eres mi decisión. Eres lo primero que se me pasa por la cabeza cuando despierto. Eres esa persona que quiero tener a mi lado todo el tiempo, quien me anima a seguir un día más.

Me pasa algo muy específico contigo, y es que no importa lo que ocurra entre nosotros, de ninguna forma puedo verte diferente. Me refiero a que nunca podría enojarme contigo al punto de no hablarte. Esto también depende mucho de mi personalidad, pero contigo se nota especialmente mi intento de resolver las cosas lo más rápido posible, porque prefiero pasar tardes enteras hablando sobre algo que te pueda pasar, que estar enojado por un mensaje que no respondiste. Siempre preferiré resolver las cosas y llenarte de buenos momentos, para que así veas lo bonito de estar conmigo.

Amo enseñarte cosas, o tal vez solo hacerlas sin darme cuenta, y que poco a poco vayas obteniendo información de eso. Siento si alguna vez digo cosas como “me copiaste eso”, porque lo que realmente quiero decir es lo hermoso que me parece que tengas partes de mi personalidad en ti; que, de alguna forma, te acostumbraste a mi presencia y ves esa parte linda de mí. De verdad, cuando dices cosas de forma inconsciente y simplemente me dejas ser yo cuando estoy contigo, es maravilloso.

Una de las cosas que más noto es cuando repito lo que dices. Sé que lo menciono mucho, pero recuerdo ese regaño inicial y cómo nunca me reprochaste nada por ello; solo te adaptaste a mi “tonta” forma de ser. Siento que eso es de lo que más aprecio: cómo te adaptas y aprendes sin quejas. No te importa estudiarme por horas, como si fuera un examen gigante o la tesis más importante de tu vida. Simplemente te tomas un tiempo para aprender de mí, y no para ser una copia, sino porque pasas tanto tiempo conmigo que siento que es natural que apliques cosas de mí a tu propia vida. Me parece maravilloso ser esa pequeña parte de ti que, no sé si será por un tiempo o para siempre, pero espero que esté en ti por mucho tiempo en ti.

Sobre este bonito narciso, no tengo mucho que decir. La realidad es que, después de una ardua investigación, lo único que encontré es que puede representar fortuna en una cultura específica. Si tuviera que basarme en lo que genera esta flor, siento que acierta muy bien, teniendo en cuenta lo afortunado que soy de tenerte. Y esto es algo que puedo decir que siempre te digo; recuerdo habértelo dicho muchas veces. Me siento muy afortunado de que me hayas elegido a mí como la persona beneficiada de tenerte.

Pero bueno, vamos a la siguiente pista, porque si no, esto nunca se va a acabar. En este caso, vamos con algo personal pero simple. Como últimamente te veo con poco tiempo, tampoco quiero ponerte cosas imposibles, así que solo te preguntaré: según como yo te llamo, ¿cómo te llamas?`
  },
loto: {
    titulo: "Flor Políglota",
    parrafos: [
      // Párrafo 1
      [`Evy, qué hermoso nombre. Te voy a dar un spoiler de lo que será esta y la siguiente carta, pero tranquila, no queda mucho; tal vez ya estás cansada de leerme tanto.`],
      // Párrafo 2
      [`Básicamente, esta carta intenta ser una respuesta a la tuya. Como ya he mencionado, hiciste referencias a la medicina, y me encantó cómo te referías a mí y a mi `, { word: "munay", translation: "Amor, querer (en quechua)" }, `. No te voy a mentir, me encantaría ser igual de ingenioso que tú y poder hacer eso con mi carrera, pero siento que decirte que eres “la nube perfecta en la cual guardaría todos mis recuerdos e información” suena medio raro.`],
      // Párrafo 3
      [`Pero, aunque suene raro, lo voy a hacer. Es interesante, porque en esta carta pienso hablar en varios lenguajes, y es gracioso porque me refiero a todo tipo de lenguajes. Una vez más, aunque de una forma diferente, mencionaré que, al leer tu carta, me di cuenta de que era probablemente el texto mejor documentado que he visto en mi vida. Te juro que he visto muchos códigos sin orden ni estructura, pero al ver tu carta, noté que, con una secuencia de algoritmos, lograste mostrar tus sentimientos de una forma espléndida.`],
      // Párrafo 4
      [`Sería redundante decir muchas cosas parecidas a las tuyas, pero es muy interesante cómo mencionas que leer mi carta fue como analizar un sistema complejo, sabiendo que no eran simplemente palabras vacías. A mí me pasó lo mismo contigo; leí y releí tu carta intentando encontrar cada vez nuevas palabras, y lo logré. Siempre veía algo nuevo y me emocionaba al pensar que en tu mente pasaban ese tipo de conjeturas.`],
      // Párrafo 5
      [`Admiré mucho tu precisión al diagnosticar mi forma de hablar. Por mi parte, aunque tu “código” tal vez no estaba hecho para resolver algo, generaste que la mayoría de los errores que se escondían dentro de mí desaparecieran. Literalmente, pareciera como si hubieras instalado un antivirus en mi `, { word: "sonqo", translation: "Corazón (en quechua)" }, `. Fue darme cuenta de que todo era real y no estaba simplemente detrás de una pantalla.`],
      // Párrafo 6
      [`Me encantó la parte en la que mencionaste que escuchas o notas mi presencia como si fueran sonidos cardíacos a los que tienes que prestarles mucha atención. Me pasa algo muy parecido contigo; intento todo el tiempo estar al tanto de lo que dices o de lo que pasa. En computación nos enseñan que, cuando envías una serie de paquetes de datos, algunos se pueden perder en el camino; a veces hay paquetes corruptos que simplemente no llegan a su destino. Pero a la hora de escucharte, siempre intento que la conexión sea lo más limpia posible, que no haya ningún tipo de interferencia y solo seamos tú y yo, conectados de un punto a otro. Eres el único paquete o mensaje que nunca voy a descartar y que siempre espero con ansias.`],
      // Párrafo 7
      [`Y solo para complementar esto con la carta anterior, es interesante que en las últimas partes mencionas que, antes de hablar de tus sentimientos, dices que todo es un análisis positivo con una evolución estable y mejoría. En mi caso, es como si todos los tests que le hice a mi sistema hubieran dado positivo. Claramente, sabemos que cuando el usuario va a probar el producto es diferente, pero de aquí hasta ese momento, intentaré probar de todas las formas posibles que esto funcione.`],
      // Párrafo 8
      [`Después de todas estas “nerdadas” raras, concluiré esta carta diciendo que amo tu forma de expresarte; es simple y compleja a la vez. Me hiciste estudiar tu carta y, al mismo tiempo, pude comprenderla la primera vez que la leí. Eres mi tema favorito para investigar; quiero saber todo de ti, pero bueno, eso ya lo sabes.`],
      // Párrafo 9
      [`Y antes de darte la última pista, sólo quería hablar un poco de la flor de loto. Siempre me pareció una `, { word: "tika", translation: "Flor (en quechua)" }, ` muy interesante por el hecho de que está en medio del agua, siempre está apuntando hacia arriba y para mí me genera mucha calma. Siento que es esa flor con sólo verla puedo sentir un poco de paz todo este tipo de sentimientos buenos son los que puedo tener contigo o en general quiero tener contigo siempre que se pueda, también se muestra un crecimiento espiritual y en general nos podemos ir a la cultura budistas para explicar el significado de esta flor pero prefiero darle el mío propio.`],
      // Párrafo 10
      [`Como última pista para la palabra, te haré una pregunta también simple, al menos para ti: ¿cómo se llama la insuficiencia cardíaca que ocurre cuando el ventrículo izquierdo del corazón no puede contraerse con la suficiente fuerza para bombear sangre adecuadamente hacia el cuerpo?`]
    ]
  },
  girasol: {
    titulo: "Flor Sentimental",
    cuerpo: `Como ya es costumbre, al final de esta carta revelaré mi "plan malévolo", porque para este punto ya es casi seguro que no podré escuchar tu reacción en vivo. Probablemente estés leyendo esto sola (o no, quién sabe). En cualquier caso, espero que hayas disfrutado la experiencia. Intenté crear cuatro flores amarillas que, aunque me costaron un poquito, creo que salieron relativamente bien (en mi humilde opinión). Claramente, lo más importante para mí es que te haya gustado y, si de alguna forma todo esto te ha encantado (o si te he encantado yo más), entonces ya cumplí mi misión.

Ahora estamos dentro del bonito girasol. Para mí, esta es una de las flores que mejor representa el amor, y es que toda esta última carta dependerá de responder a lo que mencionaste que sentías por mí en tu carta. También está de fondo la dulce Candy, la verdad me gustaría tener una rosa con tu nombre, pero ya veremos eso en el futuro.

Soy consciente de que tienes miedo a sentir demasiado, tal vez por falta de experiencia, desconfianza por situaciones previas o simplemente por tu personalidad. Aun así, me parece muy hermoso que conmigo seas más abierta a la hora de expresar tus emociones. Si te soy sincero, me encantaría que te obsesionaras conmigo; no de una forma posesiva, sino en el sentido de que entiendas que no tienes que contenerme. Mi cariño es constante, pero espero que lo veas como algo que nace de mí, no como una actitud sumisa. Hago ciertas cosas porque eres tú y quiero dedicarte todo mi ser.

Desde el momento en que leí tu carta, lo sentí. Supe que realmente existía un "nosotros" y que no era solo una percepción mía. Te lo he dicho: me gusta verte y saber de ti. Tal vez stalkearte en Instagram me convierte en un fan, pero quiero ser tu fan, no uno más. Esas pequeñas diferencias son lo que lo hacen especial para mí: que me veas como alguien que está por y para ti, y no solo un chico más (y no digo que sea así, de hecho, lo siento como algo único). Por eso me encanta recibir fotos tuyas, por eso te pongo de fondo de pantalla para tener esa pequeña parte de ti presente, por eso tengo nombres personalizados para ti... Evy.

Mencionaste que las personas nos dejan huellas: unas son como marcas de pintura que desaparecen poco a poco, para mí, otras son como tatuajes. Me parece increíble que pienses en mí. Tal vez no lo tengo tan presente, pero cuando me detengo a analizarlo, me doy cuenta de que es cierto.

Amo hacerte sonreír. Lastimosamente, no puedo verlo, pero espero con ansias el día en el que te sientas abierta a mostrármelo. Siempre intento darte la libertad de que entiendas todo lo que ocurre aquí; creo que he sido bastante directo al expresarte mis sentimientos desde el comienzo. Sé que la distancia a ti también te limita; te he escuchado decirme cosas que me harías si estuviera cerca, y es muy interesante, porque yo también las pienso. Aprovechando este momento, hablaré de la imaginación. Hasta ahora, solo te he contado momentos que he imaginado un poco 😈🔥, pero he tenido muchos otros.

Me he imaginado situaciones completamente cotidianas: te he imaginado cocinando conmigo, o en algo tan simple como cruzando una calle. Esos momentos en los que voy solo por la vida y pienso lo magnífico que sería que estuvieras a mi lado. Te he imaginado acostada junto a mí, comiendo juntos... Saber cuáles son tus expresiones dependiendo de cada situación es algo que me causa muchísima curiosidad. La imaginación, para mí, es la prueba de lo que dijiste: siempre te tengo en cuenta, siempre estás en mi mente. Cualquier situación, por más irrelevante que parezca, puede hacerme pensar en ti.

Siempre apoyaré tus sentimientos y me interesará saber cómo estás. Siendo sincero, a veces pienso que puedo dejar de gustarte en cualquier momento. Es complicado de explicar; puede que sea por situaciones entre nosotros o simplemente por mi inseguridad. Pero, de alguna forma, cada cierto tiempo suelo recibir esa versión más sincera de ti que me confirma que te fascino, entre otros muchos afectos.

Creo que ya es hora de terminar esta última carta. Solo quiero dejar claro que ha sido un placer hacer este regalo. Hay una frase que he visto mucho: "Lo único que me importa es que sepas que pensé en ti". Como cuando te envío un mensaje de "buenos días", lo que importa es que sepas que pensé en ti al despertar. Con este regalo, lo único que me importa es que sepas que pienso en ti constantemente y que tengo demasiados sentimientos hacia ti. De una forma no tan ingeniosa, te digo que estoy enamorado, pero lo que eso significa termina siendo mucho más complejo.

Como dije al comienzo, lo siento si tal vez no eran las flores amarillas que te esperabas. Para este punto, siento que me desvié mucho del camino de lo que era el "día de las flores amarillas", más que nada porque vi a mucha gente comprando ramos, pero quiero pensar que, de alguna forma, esto te puede gustar un poco más.`,
    posdata1_parte1: `Posdata: ¡Ah, casi lo olvido! Aquí hay una `,
    posdata1_link: `playlist`,
    posdata1_parte2: ` que hice para ti. No tiene muchas canciones, pero siento que cada una representa muy bien lo que siento por ti, o al menos un momento específico de lo que he llegado a sentir. Me gustaría explicarte cada canción, pero siento que ya escribí tanto que te voy a aburrir, así que, cualquier cosa te explico una por una en llamada.`,
    posdata2: `Posdata 2: Y una última cosa... puede que aún haya una palabra con pista faltando, pero eso ya lo descubriremos en el futuro.`
  },
};